// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: Hello2.proto

package grpc_go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Hello2Client is the client API for Hello2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Hello2Client interface {
	Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	Helloworld(ctx context.Context, in *HelloworldRequest, opts ...grpc.CallOption) (*HelloworldResponse, error)
}

type hello2Client struct {
	cc grpc.ClientConnInterface
}

func NewHello2Client(cc grpc.ClientConnInterface) Hello2Client {
	return &hello2Client{cc}
}

func (c *hello2Client) Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/org.test.Hello2/Heathcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hello2Client) Helloworld(ctx context.Context, in *HelloworldRequest, opts ...grpc.CallOption) (*HelloworldResponse, error) {
	out := new(HelloworldResponse)
	err := c.cc.Invoke(ctx, "/org.test.Hello2/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Hello2Server is the server API for Hello2 service.
// All implementations must embed UnimplementedHello2Server
// for forward compatibility
type Hello2Server interface {
	Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	Helloworld(context.Context, *HelloworldRequest) (*HelloworldResponse, error)
	mustEmbedUnimplementedHello2Server()
}

// UnimplementedHello2Server must be embedded to have forward compatible implementations.
type UnimplementedHello2Server struct {
}

func (UnimplementedHello2Server) Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heathcheck not implemented")
}
func (UnimplementedHello2Server) Helloworld(context.Context, *HelloworldRequest) (*HelloworldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedHello2Server) mustEmbedUnimplementedHello2Server() {}

// UnsafeHello2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Hello2Server will
// result in compilation errors.
type UnsafeHello2Server interface {
	mustEmbedUnimplementedHello2Server()
}

func RegisterHello2Server(s grpc.ServiceRegistrar, srv Hello2Server) {
	s.RegisterService(&Hello2_ServiceDesc, srv)
}

func _Hello2_Heathcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Hello2Server).Heathcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.test.Hello2/Heathcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Hello2Server).Heathcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello2_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloworldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Hello2Server).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.test.Hello2/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Hello2Server).Helloworld(ctx, req.(*HelloworldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hello2_ServiceDesc is the grpc.ServiceDesc for Hello2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hello2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org.test.Hello2",
	HandlerType: (*Hello2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heathcheck",
			Handler:    _Hello2_Heathcheck_Handler,
		},
		{
			MethodName: "Helloworld",
			Handler:    _Hello2_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Hello2.proto",
}
